name: ads_digital_partner_application_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  lottie: 2.7.0
  intl: 0.19.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/splash/
    - assets/images/walkthrough/
    - assets/images/welcome/
    - assets/images/profile/
    - assets/images/home/
    - assets/images/home/products/
    - assets/icons/
    - assets/animations/
  fonts: 
    - family: Overpass
      fonts: 
        - asset: assets/fonts/overpass/Overpass-Light.ttf
          weight: 300
        - asset: assets/fonts/overpass/Overpass-Regular.ttf
          weight: 400
        - asset: assets/fonts/overpass/Overpass-Medium.ttf
          weight: 500
        - asset: assets/fonts/overpass/Overpass-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/overpass/Overpass-Bold.ttf
          weight: 700
    - family: Hanken Grotesk
      fonts: 
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/hanken-grotesk/HankenGrotesk-Bold.ttf
          weight: 700
    - family: Sofia Pro
      fonts: 
        - asset: assets/fonts/sofiapro/sofiapro-light.otf
          weight: 300
  uses-material-design: true

